name: Preprocess Dataset
on: [push]

permissions:
  contents: write 

jobs:
  preprocess:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.7'
      - name: Install dependencies
        run: pip install pandas scikit-learn
      - name: Run preprocessing
        run: python preprocessing/automate_Zid_irsyadin.py updated_pollution_dataset_raw/updated_pollution_dataset.csv preprocessing/pollution_dataset_preprocessed_advance.csv
      - name: Commit preprocessed data
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add preprocessing/pollution_dataset_preprocessed_advance.csv
          git commit -m 'Update preprocessed dataset' || echo 'No changes to commit'
          git push